include: package:lints/recommended.yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "example/misskey_dart_flutter_app_example/**"
  errors:
    invalid_annotation_target: false
linter:
  rules:
    - directives_ordering
